# Generated by Django 4.2.3 on 2023-08-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_country_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее изменение'),
        ),
    ]
