# Generated by Django 4.2.3 on 2023-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(verbose_name='description'),
        ),
    ]
