# Generated by Django 4.2.3 on 2023-08-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_product_options_product_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.CharField(max_length=200, verbose_name='slug')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('views_count', models.IntegerField(default=0, verbose_name='views count')),
            ],
            options={
                'verbose_name': 'Posts',
                'verbose_name_plural': 'Blogues',
                'ordering': ('creation_date',),
            },
        ),
    ]
