# Generated by Django 4.2.3 on 2023-08-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_delete_customer_alter_product_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='purchase_price',
            new_name='price',
        ),
    ]
